services:
  web:
    image: httpd:latest
    container_name: web_container
    networks:
      - webnet 
    ports:
      - "3030:80"
    volumes:
      - ./app:/var/www/html

  app:
    image: myapp:latest
    container_name: app_container
    networks:
      - webnet
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: db_container
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - dbnet 

networks:
  webnet:
    driver: bridge
  dbnet:
    driver: bridge