AWSTemplateFormatVersion: '2010-09-09'
Description: Simple S3 Bucket Creation

Parameters:
  BucketName:
    Type: String
    Description: the name of the s3 bucket

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: Private