---
- name: Create Multiple Users
  hosts: all
  become: yes
  tasks:
    - name: Create Users In A Loop
      user: 
        name: "{{ item.name }}"
        state: present
        shell: /bin/bash
        password: "{{ item.password }}"
      loop: 
        - { name: 'user1', password: 'password1' }
        - { name: 'user2', password: 'password1' }
